#!/bin/sh
# Builds the modular Debian packages (astraea-service, astraea-desktop,
# astraea-gnome-shell-extension) from the staged tree in dist/stage/.
# Run ./scripts/build-linux.sh first (or let this script do it).
#
# Usage: ./scripts/build-deb.sh [--no-build]
set -eu

here="$(cd "$(dirname "$0")/.." && pwd)"
stage="$here/dist/stage"
out="$here/dist"

[ "${1:-}" = "--no-build" ] || "$here/scripts/build-linux.sh"
[ -d "$stage/usr" ] || { echo "dist/stage is empty — run scripts/build-linux.sh" >&2; exit 1; }

version="$(sed -n 's/^version: *\([0-9][^+ ]*\).*/\1/p' "$here/pubspec.yaml" | head -n1)"
arch="$(dpkg --print-architecture)"

# copy_tree PKGROOT PATH...: moves the listed staged paths into a package root.
copy_tree() {
    pkgroot="$1"; shift
    for path in "$@"; do
        [ -e "$stage/$path" ] || continue
        mkdir -p "$pkgroot/$(dirname "$path")"
        cp -a "$stage/$path" "$pkgroot/$(dirname "$path")/"
    done
}

build_pkg() {
    name="$1"; control="$2"; pkg_arch="$3"
    pkgroot="$here/dist/deb/$name"
    mkdir -p "$pkgroot/DEBIAN"
    sed -e "s/@VERSION@/$version/g" -e "s/@ARCH@/$pkg_arch/g" \
        "$here/packaging/deb/$control" > "$pkgroot/DEBIAN/control"
    if [ -f "$here/packaging/deb/postinst-${name#astraea-}" ]; then
        install -m 0755 "$here/packaging/deb/postinst-${name#astraea-}" "$pkgroot/DEBIAN/postinst"
    fi
    if [ -f "$here/packaging/deb/postrm-${name#astraea-}" ]; then
        install -m 0755 "$here/packaging/deb/postrm-${name#astraea-}" "$pkgroot/DEBIAN/postrm"
    fi
    dpkg-deb --build --root-owner-group "$pkgroot" \
        "$out/${name}_${version}_${pkg_arch}.deb" >/dev/null
    echo "built $out/${name}_${version}_${pkg_arch}.deb"
}

rm -rf "$here/dist/deb"

# astraea-service ---------------------------------------------------------
pkgroot="$here/dist/deb/astraea-service"
copy_tree "$pkgroot" \
    usr/libexec/astraea \
    usr/lib/systemd/user/astraea.service \
    usr/share/dbus-1/services/com.lwb89dev.Astraea.Service.service \
    usr/share/doc/astraea
build_pkg astraea-service control-service "$arch"

# astraea-desktop ---------------------------------------------------------
if [ -d "$stage/usr/lib/astraea" ]; then
    pkgroot="$here/dist/deb/astraea-desktop"
    copy_tree "$pkgroot" \
        usr/bin/astraea \
        usr/lib/astraea \
        usr/share/applications \
        usr/share/metainfo \
        usr/share/icons
    build_pkg astraea-desktop control-desktop "$arch"
else
    echo "skipping astraea-desktop (no flutter bundle staged)"
fi

# astraea-gnome-shell-extension ------------------------------------------
pkgroot="$here/dist/deb/astraea-gnome-shell-extension"
copy_tree "$pkgroot" usr/share/gnome-shell
build_pkg astraea-gnome-shell-extension control-gnome-extension all

# astraea-all — empty convenience metapackage (Depends only, no files) ---
if [ -d "$stage/usr/lib/astraea" ]; then
    mkdir -p "$here/dist/deb/astraea-all/DEBIAN"
    build_pkg astraea-all control-all all
else
    echo "skipping astraea-all (no astraea-desktop staged to depend on)"
fi

# Checksums + a self-contained installer, both written next to the packages
# so `dist/` can be copied or attached to a release as one unit and still be
# installable without the repository.
( cd "$out" && sha256sum ./*_"${version}"_*.deb > "SHA256SUMS-${version}" )
echo "built $out/SHA256SUMS-${version}"

cat > "$out/install.sh" <<INSTALLER
#!/bin/sh
# Installs the Astraea $version .deb packages sitting in this directory.
#
# Generated by scripts/build-deb.sh — edit that, not this file.
#
# The three packages are deliberately separate (astraea-service /
# astraea-desktop / astraea-gnome-shell-extension) so a KDE/COSMIC user can
# install without the GNOME extension and each component can be upgraded on
# its own — see docs/packaging.md. Passing all of them to a single
# \`apt install\` call is what makes the order correct: APT resolves their
# Depends against each other and installs them in dependency order no matter
# how they are listed (APT >= 1.1, i.e. every current Debian/Ubuntu/Pop!_OS).
# astraea-all is an empty metapackage that just expresses that grouping.
#
# Usage: ./install.sh [--no-extension]
#   --no-extension  skip astraea-gnome-shell-extension (and astraea-all,
#                   which depends on it being in the same transaction)
#
# Requires root (apt). It does not escalate on its own: if you are not root
# it prints the exact command to run with sudo and stops.
set -eu

here="\$(cd "\$(dirname "\$0")" && pwd)"
version="$version"
arch="$arch"
with_extension=1

for arg in "\$@"; do
    case "\$arg" in
        --no-extension) with_extension=0 ;;
        *) echo "unknown option: \$arg" >&2; exit 2 ;;
    esac
done

# Verify the packages are the ones this script was generated for before
# handing anything to apt.
if [ -f "\$here/SHA256SUMS-\$version" ]; then
    ( cd "\$here" && sha256sum -c "SHA256SUMS-\$version" ) || {
        echo "checksum mismatch — refusing to install" >&2
        exit 1
    }
else
    echo "warning: SHA256SUMS-\$version missing; installing unverified" >&2
fi

files="\$here/astraea-service_\${version}_\${arch}.deb"
[ -f "\$here/astraea-desktop_\${version}_\${arch}.deb" ] && \\
    files="\$files \$here/astraea-desktop_\${version}_\${arch}.deb"

if [ "\$with_extension" = 1 ]; then
    [ -f "\$here/astraea-gnome-shell-extension_\${version}_all.deb" ] && \\
        files="\$files \$here/astraea-gnome-shell-extension_\${version}_all.deb"
    [ -f "\$here/astraea-all_\${version}_all.deb" ] && \\
        files="\$files \$here/astraea-all_\${version}_all.deb"
fi

for f in \$files; do
    [ -f "\$f" ] || { echo "missing: \$f" >&2; exit 1; }
done

echo "==> installing:"
for f in \$files; do echo "    \$(basename "\$f")"; done

if [ "\$(id -u)" = 0 ]; then
    # shellcheck disable=SC2086
    apt install -y \$files
else
    echo
    echo "==> this needs root; re-run as:"
    echo "    sudo \$0 \$*"
    exit 1
fi

echo
echo "Done. The service starts on demand over D-Bus; launch Astraea from your"
echo "application menu, or check it with: astraea-service diagnostics"
INSTALLER
chmod 0755 "$out/install.sh"
echo "built $out/install.sh"
